/**
 * @file CryptoService.ts
 * @description Type definitions for cryptographic service interfaces within the application.
 * This file meticulously defines the expected structures for various cryptographic payloads
 * and key pairs, thereby significantly enhancing type safety, code readability,
 * and maintainability across all modules that interact with cryptographic operations.
 * It serves as a single source of truth for the shapes of encrypted data and generated keys.
 */

/**
 * @interface IAesEncrypted
 * @description Represents the standardized structure of an encrypted data payload generated
 * by an Advanced Encryption Standard (AES) operation, specifically utilizing the
 * Galois/Counter Mode (GCM). This interface is crucial for ensuring that all necessary
 * components (IV, ciphertext, authentication tag) are present for successful and secure
 * decryption, as well as for verifying the integrity and authenticity of the data.
 * @property {string} iv The **Initialization Vector (IV)**. This is a unique, randomly
 * generated value used once for each encryption operation. Represented as a hexadecimal string,
 * the IV is essential for secure decryption and prevents identical plaintext blocks from
 * encrypting to identical ciphertext blocks. It does not need to be kept secret, but must
 * be unique per encryption.
 * @property {string} encryptedData The **encrypted ciphertext**. This is the core confidential
 * data resulting from the AES encryption process, represented as a hexadecimal string.
 * It is the protected form of the original plaintext.
 * @property {string} authTag The **authentication tag**. Generated by AES GCM, this tag
 * (represented as a hexadecimal string) is appended to the ciphertext. During decryption,
 * this tag is used to cryptographically verify the integrity and authenticity of the encrypted data.
 * If the data or the tag has been tampered with, decryption will fail, providing strong
 * protection against malicious modifications.
 */
export interface IAesEncrypted {
  iv: string;
  encryptedData: string;
  authTag: string;
}

/**
 * @interface IRsaKeyPair
 * @description Defines the comprehensive structure for a generated RSA (Rivest–Shamir–Adleman)
 * public and private key pair. This interface provides a consistent and type safe way to
 * handle the fundamental components of asymmetric cryptography, which are essential for
 * secure communication, digital signatures, and key exchange protocols within the application.
 * @property {string} publicKey The **public key** of the RSA pair. This key, represented
 * in standard PEM (Privacy Enhanced Mail) format, is designed to be freely distributed.
 * It is used by others to encrypt data for the key pair owner or to verify digital signatures
 * created by the owner's corresponding private key.
 * @property {string} privateKey The **private key** of the RSA pair. This key, also
 * represented in standard PEM format, must be kept absolutely confidential and secure by
 * its owner. It is used to decrypt data that was encrypted with the corresponding public key
 * or to create digital signatures, proving the owner's identity. Compromise of this key
 * would compromise all associated encrypted data and digital signatures.
 */
export interface IRsaKeyPair {
  publicKey: string;
  privateKey: string;
}
